# Generated by Django 6.0.3 on 2026-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
